server:
  ssl:
    key-store-password: '123456'
    key-store-type: PKCS12
    key-store: classpath:keystore/mycert.p12
    enabled: 'true'
    key-alias: mycert
  port: '4443'
spring:
  jpa:
    show-sql: true
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
    driver-class-name: org.postgresql.Driver