apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-custom-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-custom-api
  template:
    metadata:
      labels:
        app: test-custom-api
    spec:
      containers:
      - image: avprokopov/test-custom-api
        name: test-custom-api
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test-custom-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080 
  selector:
    app: test-custom-api
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.test-custom-api.ap
spec:
  insecureSkipTLSVerify: true
  group: test-custom-api.ap
  groupPriorityMinimum: 1000
  versionPriority: 5
  service:
    name: test-custom-api.ap
    namespace: default
  version: v1beta1
