apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  selector:
    matchLabels:
      app: worker-app
  replicas: 4
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker-docker
        image: avprokopov/worker
        ports:
        - containerPort: 8080